name: 'solidity-metrics-action'
description: 'Generates Solidity Code Metrics Reports for Solidity Source Units in your Repository.'
inputs:
  target:
    description: 'The path of the project to analyze, relative to the repo root.'
    default: '**/*.sol'
    type: string
outputs:
  report:
    description: 'The path of the report file, relative to the repo root.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.target }}
branding:
  icon: 'file-text'  
  color: 'blue'